name: MacOS build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      duckdb_version:
        description: 'DuckDB version to build against'
        required: true
        default: 'v1.4.4'

jobs:
  build:
    name: Build Extension for MacOS
    runs-on: macos-latest

    env:
      DUCKDB_VERSION: ${{ github.event.inputs.duckdb_version }}
      EXTENSION_NAME: duckdb_rdkit

    steps:
      - name: Checkout Extension
        uses: actions/checkout@v7
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Checkout DuckDB
        run: |
          cd duckdb
          git fetch --tags
          git checkout ${{ env.DUCKDB_VERSION }}

      - name: Install System Dependencies
        run: |
          brew install cmake ninja
 
      - name: Build Extension
        shell: bash
        run: |
          GEN=ninja make release

      - name: Test Extension
        shell: bash -el {0}
        run: |
          make test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.EXTENSION_NAME }}-osx-arm64
          path: |
            build/release/extension/${{ env.EXTENSION_NAME }}/${{ env.EXTENSION_NAME }}.duckdb_extension
            build/release/duckdb

